# Generated by Django 4.1.7 on 2023-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_resume_alter_ad_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='major',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='personID',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='school',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='sex',
        ),
        migrations.AddField(
            model_name='resume',
            name='bossName',
            field=models.CharField(default=1, max_length=20, verbose_name='联系人姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='bossNum',
            field=models.CharField(default=2, max_length=20, verbose_name='联系人电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='character',
            field=models.CharField(default=3, max_length=30, verbose_name='合作肖像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='storeInfo',
            field=models.CharField(default=1, max_length=20, verbose_name='公司简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='storeName',
            field=models.CharField(default=123, max_length=20, verbose_name='公司名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='合作内容描述'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=40, verbose_name='联系地址'),
        ),
    ]
